/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Aurelius Color Palette
        'on-secondary-fixed': '#0b1c30',
        'on-primary': '#353021',
        'on-surface-variant': '#ccc6bb',
        'inverse-surface': '#e5e2e1',
        'surface': '#131313',
        'tertiary-fixed-dim': '#bcc7de',
        'on-tertiary': '#263143',
        'outline': '#959086',
        'on-surface': '#e5e2e1',
        'background': '#131313',
        'inverse-on-surface': '#313030',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'on-primary-container': '#6a6452',
        'on-secondary': '#213145',
        'surface-container-lowest': '#0e0e0e',
        'outline-variant': '#4a473e',
        'on-tertiary-fixed': '#111c2d',
        'surface-variant': '#353534',
        'surface-dim': '#131313',
        'on-error-container': '#ffdad6',
        'secondary-container': '#3a4a5f',
        'surface-tint': '#cec6b0',
        'on-primary-fixed-variant': '#4c4736',
        'primary-fixed-dim': '#cec6b0',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-container': '#5a6579',
        'error-container': '#93000a',
        'on-secondary-fixed-variant': '#38485d',
        'secondary': '#b7c8e1',
        'surface-bright': '#3a3939',
        'on-primary-fixed': '#1f1b0e',
        'on-secondary-container': '#a9bad3',
        'on-background': '#e5e2e1',
        'primary-container': '#ebe2cb',
        'tertiary-container': '#d8e3fb',
        'primary-fixed': '#ebe2cb',
        'surface-container-highest': '#353534',
        'on-error': '#690005',
        'tertiary-fixed': '#d8e3fb',
        'tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#3c475a',
        'primary': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        'inverse-primary': '#645e4c',
        'error': '#ffb4ab',
        'secondary-fixed': '#d3e4fe',
        // Aurelius Accent Gold
        'accent': '#F3EAD3',
        'accent-gold': '#F3EAD3',
        'accent-dark': '#d4c5a9',
      },
      fontFamily: {
        'montserrat': ['Montserrat', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', fontWeight: '700', letterSpacing: '0px' }],
        'display-lg-mobile': ['45px', { lineHeight: '52px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'xs': '4px',
        'base': '8px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'container-max': '1280px',
      },
      animation: {
        blob: 'blob 7s infinite',
        float: 'float 3s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'fade-in': 'fade-in 0.5s ease-out',
        'slide-in-from-bottom': 'slide-in-from-bottom 0.3s ease-out',
      },
      keyframes: {
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '25%': { transform: 'translate(20px, -50px) scale(1.1)' },
          '50%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '75%': { transform: 'translate(50px, 50px) scale(1.05)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(192, 193, 255, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(192, 193, 255, 0.6)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
